version: '3.7'

x-silent: &silent
    logging:
        driver: 'none'

services:
    redis:
        image: redis:latest
        <<: *silent

    mongo:
        image: mongo:latest
        <<: *silent

    mysql:
        image: mysql:5
        <<: *silent
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_USER: mysql
            MYSQL_PASSWORD: endb
            MYSQL_DATABASE: endb_test

    postgres:
        image: postgres:latest
        <<: *silent
        command: ['-c', 'max_connections=200']
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: endb
            POSTGRES_DB: endb_test

    test:
        build: .
        environment:
            REDIS_HOST: redis
            MONGO_HOST: mongo
            POSTGRES_HOST: postgres
            POSTGRES_PASSWORD: endb
            MYSQL_HOST: mysql
            MYSQL_PASSWORD: endb
        depends_on:
            - redis
            - mongo
            - mysql
            - postgres
        volumes:
            - ./:/repo